package BBDDpackage;

public class ConstantQuery {
	//QUERYS DRIVER
	public static final String INSERT_DRIVER = "INSERT INTO STUCOMBUS.CONDUCTOR (DNI, NOMBRE, APELLIDO) VALUES (?,?,?)";
	public static final String GET_DRIVER = "SELECT DNI, NOMBRE, APELLIDO FROM STUCOMBUS.CONDUCTOR";
	public static final String DELETE_DRIVER = "DELETE FROM STUCOMBUS.CONDUCTOR WHERE DNI LIKE (?)";
	
	//QUERYS VEHICLE
	public static final String INSERT_VEHICLE = "INSERT INTO STUCOMBUS.AUTOBUS (MATRICULA, ASIENTOS) VALUES (?,?)";
	public static final String GET_VEHICLE = "SELECT MATRICULA, ASIENTOS FROM STUCOMBUS.AUTOBUS";
	public static final String DELETE_VEHICLE = "DELETE FROM STUCOMBUS.AUTOBUS WHERE MATRICULA LIKE (?)";
	public static final String UPDATE_SEATS = "UPDATE STUCOMBUS.AUTOBUS SET ASIENTOS = (?) WHERE MATRICULA LIKE (?)";
	
	//QUERYS PASSENGER
	public static final String INSERT_PASSENGER = "INSERT INTO STUCOMBUS.PASAJERO (DNI, NOMBRE, APELLIDO) VALUES (?,?,?)";
	public static final String GET_PASSENGER = "SELECT DNI, NOMBRE, APELLIDO FROM STUCOMBUS.PASAJERO";
	public static final String DELETE_PASSENGER = "DELETE FROM STUCOMBUS.PASAJERO WHERE DNI LIKE (?)";
	
	//QUERYS City
	public static final String GET_CITY = "SELECT ID, NOMBRE FROM STUCOMBUS.CIUDAD";
	
	//QUERYS ROUTE
	public static final String INSERT_ROUTE = "INSERT INTO STUCOMBUS.RUTA (IDRUTA, MATRICULA, CONDUCTORDNI, FECHA_SALIDA, FECHA_LLEGADA, CIUDAD_ORIGEN, CIUDAD_DESTINO) VALUES (?,?,?,?,?,?,?);";
	public static final String GET_ROUTE = "SELECT IDRUTA, MATRICULA, CONDUCTORDNI, FECHA_SALIDA, FECHA_LLEGADA, CIUDAD_ORIGEN, CIUDAD_DESTINO FROM STUCOMBUS.RUTA";
	public static final String DELETE_ROUTE = "DELETE FROM STUCOMBUS.RUTA WHERE IDRUTA LIKE (?)";
	
	//QUERYS ROUTE-PASSENGER
	public static final String INSERT_ROUTE_PASSENGER = "INSERT INTO STUCOMBUS.PASAJEROSRUTA (DNIPASAJERO, IDRUTA, IDPASAJERORUTA) VALUES (?,?,?)";
	public static final String GET_ID_PASSENGER_ROUTE = "SELECT IDPASAJERORUTA FROM STUCOMBUS.PASAJEROSRUTA";
	public static final String GET_PASSENGER_ROUTE = "SELECT DNIPASAJERO, IDRUTA, IDPASAJERORUTA FROM STUCOMBUS.PASAJEROSRUTA";
	public static final String DELETE_PASSENGER_ROUTE = "DELETE FROM STUCOMBUS.PASAJEROSRUTA WHERE DNIPASAJERO LIKE (?)";

	
	
}
